### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by TodePond** [TodePond/NewPond#1]
## Music
- [x] Far Away Place - Jody Wisternoff & James Grant Extended Mix
- [x] The Sky Calls To Us - Jody Wisternoff & James Grant Extended Remix
- [x] Santorini - Fingerprint & Spencer Brown
- [x] Pacific - Jaytech
- [x] Screwdriver - Above & Beyond

## Code
- [x] PaintPond
- [x] Game of Living
- [x] Wilson Codes
- [x] LNCA
- [x] Cableworld
- [x] Luke's Ant
- [x] RedGreenBluegene

## Script
- [x] Intro
- [x] Game of Living
- [x] Wilson Codes
- [x] LNCA
- [x] Cableworld
- [x] Luke's Ant
- [x] RedGreenBluegene
- [x] Outro

## Audio
- [x] Intro
- [x] Game of Living
- [x] Wilson Codes
- [x] LNCA
- [x] Cableworld
- [x] Luke's Ant
- [x] RedGreenBluegene
- [x] Outro

## Block
- [x] Transitions
- [x] Intro
- [x] Game of Living
- [x] Wilson Codes
- [x] LNCA
- [x] Cableworld
- [x] Luke's Ant
- [x] RedGreenBluegene
- [x] Outro
- [x] Credits

## Social Media
- [x] Twitter
- [x] Discord
- [x] Reddit
- [x] Instagram
- [x] Hackernews
- [x] Youtube

## Starfields
- [x] Twitter
- [x] Discord
- [x] Reddit
- [x] Instagram
- [x] Hackernews
- [x] Youtube

## Transitions
- [x] Twitter
- [x] Discord
- [x] Reddit
- [x] Instagram
- [x] Hackernews
- [x] Youtube

## Video
- [x] Writing
- [x] Intro
- [x] Game of Living
- [x] Wilson Codes
- [x] LNCA
- [x] Cableworld
- [x] Luke's Ant
- [x] RedGreenBluegene
- [x] Outro
- [x] Outro continuation
- [x] Credits
- [x] Post-Credits Scene

**Comment by TodePond** [comment]
Code for PaintPond done: https://github.com/TodePond/PaintPond

Next, I'll finish up LNCA

**Comment by TodePond** [comment]
I think that's enough LNCA work for now - I could spend a long time exploring that but I better move on :)

**Comment by TodePond** [comment]
Time to make CableWorld

**Comment by TodePond** [comment]
CableWorld done! Next: Luke's Ant

**Comment by TodePond** [comment]
Luke's Ant done! Next up: Lu's Loops! I think I will cancel Falling Dust Game because I've done similar things a lot before - and it doesn't lead on as well as the others

**Comment by TodePond** [comment]
I did RedGreenBluegene instead! Um-ing and ah-ing about whether to do the final two or just skip them and make the video

**Comment by TodePond** [comment]
Yeah I think I'll leave the code there! Time to make the video!

**Comment by TodePond** [comment]
Audio of intro and Game of Living done!

**Comment by TodePond** [comment]
Script for Wilson Codes done

**Comment by TodePond** [comment]
Audio for Wilson Codes done!

**Comment by TodePond** [comment]
Script + Audio of LNCA done!

**Comment by TodePond** [comment]
Script + Audio of Cableworld done!

**Comment by TodePond** [comment]
ALL AUDIO DONE!

**Comment by TodePond** [comment]
A lot more blocking done!

**Comment by TodePond** [comment]
Writing transitions done!!!

**Comment by TodePond** [comment]
Video for intro and done (and beginning of game of living)

**Comment by TodePond** [comment]
twitter done! it took a long time but also it looks really good

**Comment by TodePond** [comment]
Discord done!

**Comment by TodePond** [comment]
Now that I've got the hang of it, I'll make all the fake social media posts first (before I make the video transitions). This should speed it up

**Comment by TodePond** [comment]
Reddit = done

**Comment by TodePond** [comment]
Hackernews assets done

**Comment by TodePond** [comment]
Instagram assets done

**Comment by TodePond** [comment]
All social media assets done!

**Comment by TodePond** [comment]
Making all the starfields now - reddit done

**Comment by TodePond** [comment]
Instagram starfield done

**Comment by TodePond** [comment]
I re-did the instagram starfield

**Comment by TodePond** [comment]
Hackernews starfield done!

**Comment by TodePond** [comment]
youtube starfield done!

**Comment by TodePond** [comment]
Post-credits scene done!

**Comment by TodePond** [comment]
Credits done

**Comment by TodePond** [comment]
Reddit + Instagram transitions done

**Comment by TodePond** [comment]
Hackernews transition done

**Comment by TodePond** [comment]
All transitions done now! I think I'll do the outro + continuation next

**Comment by TodePond** [comment]
Outro continuation done

**Comment by TodePond** [comment]
Outro done!!!

**Comment by TodePond** [comment]
Wilson Code blocked out

**Comment by TodePond** [comment]
LNCA blocked

**Comment by TodePond** [comment]
Cableworld blocked

**Comment by TodePond** [comment]
ant blocked

**Comment by TodePond** [comment]
The whole video is blocked out now! Now it's time for some quick colour-by-numbers to FINISH THIS VIDEO

**Comment by Magnogen** [comment]
IT'S HAPPENING YOOOOO

**Comment by TodePond** [comment]
Yes hooray! No checkpoints today though - been making visuals in preparation for the last bits :)

**Comment by TodePond** [comment]
Game of Living done!

**Comment by TodePond** [comment]
Wilson Code done!

**Comment by TodePond** [comment]
Final post-credits assets inserted

**Comment by TodePond** [comment]
LNCA done! that's the biggest sections finished

**Comment by TodePond** [comment]
Cableworld done! getting closer... almost there...

**Comment by TodePond** [comment]
Luke's ant done! Time for the last section!

**Comment by TodePond** [comment]
It's done! gonna check everything and render and upload

**Comment by Magnogen** [comment]
Beautiful video! Looking forward to the next one!

**Comment by TodePond** [comment]
Thanks! Me too :)

hopping over to https://github.com/TodePond/ScreenPond
